-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 11:08:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sctu_sqldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sctu_sqldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sctu_sqldb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sctu_sqldb` ;

-- -----------------------------------------------------
-- Table `sctu_sqldb`.`study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`study` (
  `idStudy` INT NOT NULL AUTO_INCREMENT,
  `StudyName` VARCHAR(45) NOT NULL,
  `Disease` VARCHAR(45) NULL DEFAULT NULL,
  `Treatment` VARCHAR(255) NULL DEFAULT NULL,
  `Funder` VARCHAR(45) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `Abstract` TEXT NULL DEFAULT NULL,
  `Git` TEXT NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `DocumentsLocation` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idStudy`),
  UNIQUE INDEX `idStudy_UNIQUE` (`idStudy` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This is the main table of the database holding information about a study and other associated information relevant here.';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`subject` (
  `idUnit` INT NOT NULL AUTO_INCREMENT COMMENT 'a unit of analysis - it is typically a combination of subject id, and visit for each study',
  `idAnonymised` INT NOT NULL COMMENT 'anonymised database id from external source',
  `Visit` INT NOT NULL COMMENT 'visit number ',
  `idStudy` INT NOT NULL,
  PRIMARY KEY (`idUnit`),
  UNIQUE INDEX `uc_idAnonymised_Visit_idStudy` (`idAnonymised` ASC, `Visit` ASC, `idStudy` ASC) INVISIBLE,
  UNIQUE INDEX `idUnit_UNIQUE` (`idUnit` ASC) VISIBLE,
  INDEX `fk_Subject_Study1_idx` (`idStudy` ASC) INVISIBLE,
  CONSTRAINT `fk_Subject_Study1`
    FOREIGN KEY (`idStudy`)
    REFERENCES `sctu_sqldb`.`study` (`idStudy`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table will contain information about each unit of analysis. Typically this will be a combination of subject id and the visit number.';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`clinicaldata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`clinicaldata` (
  `idClinicalData` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NOT NULL,
  `Value` VARCHAR(255) NULL DEFAULT NULL,
  `idUnit` INT NOT NULL,
  `idStudy` INT NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idClinicalData`),
  UNIQUE INDEX `idClinicalData_UNIQUE` (`idClinicalData` ASC) VISIBLE,
  INDEX `fk_ClinicalData_Subject1_idx` (`idUnit` ASC) VISIBLE,
  INDEX `fk_ClinicalData_Study1_idx` (`idStudy` ASC) VISIBLE,
  CONSTRAINT `fk_ClinicalData_Study1`
    FOREIGN KEY (`idStudy`)
    REFERENCES `sctu_sqldb`.`study` (`idStudy`),
  CONSTRAINT `fk_ClinicalData_Subject1`
    FOREIGN KEY (`idUnit`)
    REFERENCES `sctu_sqldb`.`subject` (`idUnit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Table to hold all clinical and demographic data and any metadata related to a unit of analysis';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`dataset` (
  `idDataset` INT NOT NULL AUTO_INCREMENT,
  `idStudy` INT NOT NULL,
  `OmicsDataType` VARCHAR(255) NOT NULL,
  `Tissue` VARCHAR(45) NULL DEFAULT NULL,
  `Git` TEXT NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Instrument` VARCHAR(255) NULL DEFAULT NULL,
  `ProcessingSteps` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idDataset`),
  UNIQUE INDEX `idDataset_UNIQUE` (`idDataset` ASC) VISIBLE,
  INDEX `fk_Dataset_Study1_idx` (`idStudy` ASC) VISIBLE,
  CONSTRAINT `fk_Dataset_Study1`
    FOREIGN KEY (`idStudy`)
    REFERENCES `sctu_sqldb`.`study` (`idStudy`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Each study can have multiple omics data sets and related information will go here';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`omicssample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`omicssample` (
  `idOmicsSample` INT NOT NULL AUTO_INCREMENT COMMENT 'each sample belongs to one unit of analysis',
  `idDataset` INT NOT NULL,
  `idUnit` INT NOT NULL,
  PRIMARY KEY (`idOmicsSample`),
  UNIQUE INDEX `idSample_UNIQUE` (`idOmicsSample` ASC) VISIBLE,
  INDEX `fk_Sample_Dataset1_idx` (`idDataset` ASC) VISIBLE,
  INDEX `fk_Sample_Subject1_idx` (`idUnit` ASC) VISIBLE,
  CONSTRAINT `fk_Sample_Dataset1`
    FOREIGN KEY (`idDataset`)
    REFERENCES `sctu_sqldb`.`dataset` (`idDataset`),
  CONSTRAINT `fk_Sample_Subject1`
    FOREIGN KEY (`idUnit`)
    REFERENCES `sctu_sqldb`.`subject` (`idUnit`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Each Omics Sample belongs to a dataset. It also belongs to a unit of analysis i.e. Subject_idUnit. One unit of analysis can have multiple samples if technical replicates were produced i.e. a biological sample from a subject sequenced multiple times.';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`datalevel0`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`datalevel0` (
  `idDataLevel0` INT NOT NULL AUTO_INCREMENT,
  `idSample` INT NOT NULL,
  `FileName` TEXT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Location` TEXT NOT NULL,
  PRIMARY KEY (`idDataLevel0`),
  UNIQUE INDEX `idDataLevel0_UNIQUE` (`idDataLevel0` ASC) VISIBLE,
  INDEX `fk_DataLevel0_Sample1_idx` (`idSample` ASC) VISIBLE,
  CONSTRAINT `fk_DataLevel0_Sample1`
    FOREIGN KEY (`idSample`)
    REFERENCES `sctu_sqldb`.`omicssample` (`idOmicsSample`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Each Sample has an associated raw data file or more than one e.g. a RNA-Seq sample will have two FASTQ files';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`datalevel1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`datalevel1` (
  `idDataLevel1` INT NOT NULL AUTO_INCREMENT,
  `idDataset` INT NOT NULL,
  `FileName` TEXT NOT NULL,
  `Type` VARCHAR(45) NOT NULL COMMENT 'short description of file type e.g. vcf, count matrix etc.',
  `Location` TEXT NOT NULL COMMENT 'folder path where it is saved',
  `ProcessingSteps` TEXT NULL DEFAULT NULL COMMENT 'how was this file generated, any comments or git repository link',
  PRIMARY KEY (`idDataLevel1`),
  UNIQUE INDEX `idDataLevel1_UNIQUE` (`idDataLevel1` ASC) VISIBLE,
  INDEX `fk_DataLevel1_Dataset1_idx` (`idDataset` ASC) VISIBLE,
  CONSTRAINT `fk_DataLevel1_Dataset1`
    FOREIGN KEY (`idDataset`)
    REFERENCES `sctu_sqldb`.`dataset` (`idDataset`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This contains the processed data in a self contained format e.g. the count matrix with associated metadata all in the form of a R or SAS etc object. This is analysis ready data.';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`omicssamplemetadata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`omicssamplemetadata` (
  `idOmicsSampleMetaData` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NOT NULL,
  `Value` VARCHAR(255) NULL DEFAULT NULL,
  `idOmicsSample` INT NOT NULL,
  `Description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idOmicsSampleMetaData`),
  UNIQUE INDEX `id_UNIQUE` (`idOmicsSampleMetaData` ASC) VISIBLE,
  INDEX `fk_MetadataSample_Sample1_idx` (`idOmicsSample` ASC) VISIBLE,
  CONSTRAINT `fk_MetadataSample_Sample1`
    FOREIGN KEY (`idOmicsSample`)
    REFERENCES `sctu_sqldb`.`omicssample` (`idOmicsSample`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'The metadata related to the omics sample. this usually will be the lab associated additional information e.g. Sequencing lanes, batches, RNA-quality etc';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`results` (
  `idResults` INT NOT NULL AUTO_INCREMENT,
  `idStudy` INT NOT NULL,
  `idDataset` INT NULL DEFAULT NULL COMMENT 'this can be null as a result may not be linked to a single data set directly and can be more general',
  `Location` TEXT NULL DEFAULT NULL COMMENT 'a folder path where the result file is stored',
  `FileName` TEXT NULL DEFAULT NULL,
  `Git` TEXT NULL DEFAULT NULL COMMENT 'any further information that may need to be added related to the results on the associated github repository',
  `ProcessingSteps` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idResults`),
  UNIQUE INDEX `idResults_UNIQUE` (`idResults` ASC) VISIBLE,
  INDEX `fk_Results_Study1_idx` (`idStudy` ASC) VISIBLE,
  INDEX `fk_Results_Dataset1_idx` (`idDataset` ASC) VISIBLE,
  CONSTRAINT `fk_Results_Dataset1`
    FOREIGN KEY (`idDataset`)
    REFERENCES `sctu_sqldb`.`dataset` (`idDataset`),
  CONSTRAINT `fk_Results_Study1`
    FOREIGN KEY (`idStudy`)
    REFERENCES `sctu_sqldb`.`study` (`idStudy`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'Results table with links to figures, reports excel sheets and misc';


-- -----------------------------------------------------
-- Table `sctu_sqldb`.`studysampletype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sctu_sqldb`.`studysampletype` (
  `idStudySampleType` INT NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(255) NULL DEFAULT NULL,
  `TranslationalWork` TEXT NULL DEFAULT NULL,
  `idStudy` INT NOT NULL,
  PRIMARY KEY (`idStudySampleType`),
  UNIQUE INDEX `id_UNIQUE` (`idStudySampleType` ASC) VISIBLE,
  INDEX `fk_StudySampleType_Study_idx` (`idStudy` ASC) VISIBLE,
  CONSTRAINT `fk_StudySampleType_Study`
    FOREIGN KEY (`idStudy`)
    REFERENCES `sctu_sqldb`.`study` (`idStudy`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table contains additional information about the type of translational data e.g. a study can collect multiple types of data and some general information can be held in this table';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
